-- Fraud detection: payment-channel cross-check (แจ้งบัญชีรับเงินส่วนตัว).
-- The LLM only EXTRACTS payment-channel mentions from the transcript
-- (UnifiedPipelineAgent "fraud_signals"); the verdict is computed deterministically in PHP
-- by FraudCheckService against primacom_mini_erp.bank_account — never by the model.
-- Rows here are "suspicious items for human review", not automatic accusations:
-- review_status tracks the human decision.

CREATE TABLE IF NOT EXISTS fraud_checks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  conversation_id INT NOT NULL,
  company_id INT NOT NULL COMMENT 'erp company id (primacom_mini_erp.companies.id)',
  check_type VARCHAR(50) NOT NULL DEFAULT 'payment_channel',
  source ENUM('llm','regex') NOT NULL DEFAULT 'llm' COMMENT 'llm = extracted by UnifiedPipelineAgent, regex = digit-run safety net over the raw transcript',
  status ENUM('flagged','clear') NOT NULL DEFAULT 'flagged' COMMENT 'clear = mention matched an official company account (recorded, not alarming)',
  risk_level ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  channel_type VARCHAR(30) NULL COMMENT 'bank_account|promptpay|line_id|wallet|other|number_sequence',
  detected_value VARCHAR(255) NULL COMMENT 'normalized: digits only for account/promptpay, raw id for line_id',
  bank_name VARCHAR(100) NULL,
  spoken_by ENUM('employee','customer','unknown') NULL,
  purpose TEXT NULL COMMENT 'why the channel was given, per the LLM (Thai)',
  evidence TEXT NULL COMMENT 'verbatim transcript quote',
  explanation TEXT NULL COMMENT 'deterministic verdict explanation generated by FraudCheckService (Thai)',
  matched_bank_account_id INT NULL COMMENT 'primacom_mini_erp.bank_account.id when matched (no cross-DB FK possible)',
  review_status ENUM('pending','confirmed','dismissed') NOT NULL DEFAULT 'pending',
  reviewed_by INT NULL COMMENT 'erp user id of the reviewer',
  reviewed_by_name VARCHAR(255) NULL,
  review_note TEXT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_fraud_conv (conversation_id),
  KEY idx_fraud_company (company_id),
  KEY idx_fraud_review (review_status),
  KEY idx_fraud_risk (risk_level),
  KEY idx_fraud_status (status),
  CONSTRAINT fk_fraud_conv FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
